// Hand-authored types reflecting the live TS-HR Supabase schema (project yclhzwghzrohusqxfasq).
// Regenerate with `supabase gen types typescript` once the schema stabilises further.

export type UserRole = 'owner' | 'entity_admin' | 'location_manager' | 'staff'

export type EmployeeStatus = 'candidate' | 'pre_boarding' | 'active' | 'inactive'
export type EmploymentType = 'full_time' | 'part_time' | 'on_call' | 'seasonal'

export interface Profile {
  id: string
  full_name: string | null
  role: UserRole
  entity_id: string | null
  location_id: string | null
  created_at: string
  /** false once access is revoked / the employee is inactivated. */
  is_active?: boolean | null
}

export interface Entity {
  id: string
  name: string
  trade_license_no: string | null
  emirate: string | null
  default_currency: string | null
  created_at: string
}

export interface Location {
  id: string
  entity_id: string
  name: string
  address: string | null
  created_at: string
}

export interface Position {
  id: string
  entity_id: string
  title: string
  department: string | null
  created_at: string
}

export interface Employee {
  id: string
  entity_id: string
  home_location_id: string | null
  position_id: string | null
  auth_user_id: string | null
  full_name: string
  preferred_name: string | null
  photo_url: string | null
  dob: string | null
  gender: string | null
  nationality: string | null
  phone: string | null
  email: string | null
  emergency_contact_name: string | null
  emergency_contact_phone: string | null
  passport_exp: string | null
  visa_exp: string | null
  labor_card_exp: string | null
  health_card_exp: string | null
  employment_type: EmploymentType | null
  employment_status: EmployeeStatus | null
  join_date: string | null
  probation_end_date: string | null
  notes: string | null
  created_at: string
  updated_at: string
  // relations commonly joined in the directory view
  locations?: Pick<Location, 'id' | 'name'> | null
  positions?: Pick<Position, 'id' | 'title' | 'department'> | null
}

export interface LeaveRequest {
  id: string
  employee_id: string
  leave_type_id: string
  start_date: string
  end_date: string
  days_requested: number
  status: 'pending' | 'approved' | 'rejected' | 'cancelled'
  reason: string | null
  requested_at: string
  decided_by: string | null
  decided_at: string | null
  manager_notes: string | null
  employees?: Pick<Employee, 'id' | 'full_name'> | null
  leave_types?: Pick<LeaveType, 'id' | 'name'> | null
}

export interface LeaveType {
  id: string
  entity_id: string
  name: string
  accrual_days_per_year: number
  requires_approval: boolean
  created_at: string
}

export interface LeaveBalance {
  id: string
  employee_id: string
  leave_type_id: string
  balance_days: number
  updated_at: string | null
  leave_types?: Pick<LeaveType, 'id' | 'name'> | null
}

export type DocumentReviewStatus = 'pending_review' | 'approved' | 'rejected' | 'superseded' | 'archived'

export interface EmployeeDocument {
  id: string
  employee_id: string
  doc_type: string
  storage_path: string
  expiry_date: string | null
  notes: string | null
  review_status: DocumentReviewStatus
  version_number: number
  supersedes_document_id: string | null
  is_current: boolean
  submitted_by: string | null
  submitted_at: string
  reviewed_by: string | null
  reviewed_at: string | null
  rejection_reason: string | null
  archived_at: string | null
  archived_by: string | null
  created_at: string
  updated_at: string
  // Phase 2.10: false until confirm_document_upload() has independently
  // verified the file actually exists in storage. A location_manager's view
  // of a sensitive doc_type comes back through get_documents_for_review()
  // with storage_path (and notes) nulled out rather than this flag — check
  // `!doc.storage_path` to decide whether a "View" action is available.
  upload_confirmed?: boolean
  uploaded_by?: string | null
  upload_method?: 'self' | 'assisted' | null
  employees?: Pick<Employee, 'id' | 'full_name'> | null
}

export interface EmployeeChangeRequest {
  id: string
  employee_id: string
  field_name: string
  old_value: string | null
  new_value: string
  reason: string | null
  status: 'pending' | 'approved' | 'rejected'
  requested_at: string
  decided_by: string | null
  decided_at: string | null
  decision_reason: string | null
  employees?: Pick<Employee, 'id' | 'full_name'> | null
}

export type ShiftStatus = 'open' | 'assigned' | 'cancelled'

export interface Shift {
  id: string
  entity_id: string
  location_id: string
  position_id: string | null
  employee_id: string | null
  shift_date: string
  start_time: string
  end_time: string
  break_minutes: number
  status: ShiftStatus
  notes: string | null
  created_by: string | null
  created_at: string | null
  // Phase 2.6: a shift generated by generate_shifts_from_templates() starts
  // out unpublished (is_published = false, a "Draft") and is invisible to
  // the assigned employee (enforced by RLS, not just hidden in the UI) until
  // a manager/admin calls publish_schedule_period(). Manually-created shifts
  // default to is_published = true (already visible), unchanged from before
  // this phase. generated_from_template_id links back to the recurring
  // template that produced it, or is null for an ad-hoc shift.
  is_published: boolean
  generated_from_template_id: string | null
  locations?: Pick<Location, 'id' | 'name'> | null
  positions?: Pick<Position, 'id' | 'title'> | null
  employees?: Pick<Employee, 'id' | 'full_name'> | null
}

export type ShiftChangeType = 'cancelled' | 'unpublished' | 'reassigned' | 'date_changed' | 'location_changed' | 'time_changed' | 'break_changed' | 'deleted' | 'absence_reported'

export interface ShiftAdjustment {
  id: string
  shift_id: string
  entity_id: string
  location_id: string | null
  employee_id: string | null
  previous_employee_id: string | null
  change_type: ShiftChangeType
  reason: string | null
  old_values: Record<string, unknown>
  new_values: Record<string, unknown> | null
  changed_by: string | null
  changed_at: string
}

// Phase 2.6: recurring weekly schedule templates. day_of_week follows
// Postgres EXTRACT(dow): 0 = Sunday .. 6 = Saturday. Versioned like
// employee_documents — editing calls replace_schedule_template(), which
// deactivates the old row and inserts a new one with version_number + 1 and
// supersedes_template_id pointing back; there is no in-place update.
export interface ScheduleTemplate {
  id: string
  entity_id: string
  location_id: string
  employee_id: string
  position_id: string | null
  day_of_week: number
  start_time: string
  end_time: string
  break_minutes: number
  effective_start_date: string
  effective_end_date: string | null
  version_number: number
  supersedes_template_id: string | null
  is_active: boolean
  created_by: string | null
  created_at: string
  updated_at: string
  employees?: Pick<Employee, 'id' | 'full_name'> | null
  positions?: Pick<Position, 'id' | 'title'> | null
}

export interface ShiftSwapRequest {
  id: string
  shift_id: string
  requested_by: string
  claimed_by: string | null
  status: 'open' | 'claimed' | 'approved' | 'rejected' | 'cancelled'
  notes: string | null
  created_at: string | null
  resolved_by: string | null
  resolved_at: string | null
  shifts?: Pick<Shift, 'id' | 'shift_date' | 'start_time' | 'end_time' | 'location_id'> & {
    locations?: Pick<Location, 'id' | 'name'> | null
  }
  requester?: Pick<Employee, 'id' | 'full_name'> | null
  claimant?: Pick<Employee, 'id' | 'full_name'> | null
}

export type PayrollRunStatus = 'draft' | 'in_review' | 'approved' | 'paid'
export type TipDistributionRule = 'equal' | 'hours_weighted' | 'role_weighted'

export interface PayrollRun {
  id: string
  entity_id: string
  period_start: string
  period_end: string
  status: PayrollRunStatus
  tip_distribution_rule: TipDistributionRule
  created_by: string | null
  created_at: string
  approved_by: string | null
  approved_at: string | null
  overtime_holiday_pay_confirmed: boolean
  tips_distribution_confirmed: boolean
  // Set only by create_payroll_revision(); links a correction run back to the
  // approved/paid run it revises. The source run's own snapshot (and its
  // timesheet/tips/deduction rows) is never mutated -- corrections always
  // happen in the new, separately-editable draft run this points from.
  revises_payroll_run_id?: string | null
}

export interface PayrollRunTotals {
  payroll_run_id: string
  entity_id: string
  period_start: string
  period_end: string
  status: PayrollRunStatus
  employee_count: number
  total_base_pay: number
  total_overtime_pay: number
  total_holiday_pay: number
  total_tips: number
  total_deductions: number
  total_net_pay: number
}

export interface TimesheetEntry {
  id: string
  payroll_run_id: string
  employee_id: string
  regular_hours: number
  overtime_hours: number
  holiday_hours: number
  notes: string | null
  employees?: Pick<Employee, 'id' | 'full_name'> | null
}

export interface TipsPool {
  id: string
  payroll_run_id: string
  location_id: string
  total_amount: number
  notes: string | null
  updated_at: string
  locations?: Pick<Location, 'id' | 'name'> | null
}

export interface Payslip {
  id: string
  payroll_run_id: string
  employee_id: string
  base_pay: number
  overtime_pay: number
  holiday_pay: number
  tips_share: number
  total_deductions: number
  net_pay: number
  generated_at: string
  employees?: Pick<Employee, 'id' | 'full_name'> | null
}

export type RequisitionStatus = 'draft' | 'open' | 'on_hold' | 'closed' | 'cancelled'
export type CandidateSource = 'referral' | 'walk_in' | 'online' | 'agency' | 'other'
export type CandidateStatus = 'new' | 'screening' | 'interviewing' | 'offer' | 'hired' | 'rejected' | 'withdrawn'
export type ApplicationStage = CandidateStatus
export type InterviewOutcome = 'pending' | 'pass' | 'fail'
export type OfferStatus = 'draft' | 'sent' | 'accepted' | 'declined' | 'rescinded'

export interface JobRequisition {
  id: string
  entity_id: string
  location_id: string
  position_id: string
  headcount: number
  status: RequisitionStatus
  created_by: string | null
  created_at: string
  opened_by: string | null
  opened_at: string | null
  closed_by: string | null
  closed_at: string | null
  locations?: Pick<Location, 'id' | 'name'> | null
  positions?: Pick<Position, 'id' | 'title' | 'department'> | null
}

export interface Candidate {
  id: string
  entity_id: string
  location_id: string | null
  full_name: string
  contact_email: string | null
  contact_phone: string | null
  source: CandidateSource
  resume_url: string | null
  status: CandidateStatus
  created_by: string | null
  created_at: string
  updated_at: string
}

export interface JobApplication {
  id: string
  requisition_id: string
  candidate_id: string
  applied_at: string
  stage: ApplicationStage
  rejection_reason: string | null
  candidates?: Pick<Candidate, 'id' | 'full_name' | 'contact_email' | 'contact_phone' | 'source'> | null
}

export interface InterviewStage {
  id: string
  requisition_id: string
  sequence: number
  name: string
}

export interface Interview {
  id: string
  application_id: string
  stage_id: string
  scheduled_at: string
  interviewer_id: string
  outcome: InterviewOutcome
  notes: string | null
  recorded_by: string | null
  recorded_at: string | null
  format: InterviewFormat
  meeting_location: string | null
  cancelled_at: string | null
  cancelled_by: string | null
  cancellation_reason: string | null
  // Links a rescheduled interview back to the one it replaced (mirrors
  // employee_documents.supersedes_document_id). Set by reschedule_interview();
  // never written directly by the client.
  rescheduled_from_interview_id: string | null
  interview_stages?: Pick<InterviewStage, 'id' | 'name' | 'sequence'> | null
  // Feedback is deliberately NOT embedded here anymore (Phase 3.12). It used
  // to come along for free via the interview_feedback -> interviews FK under
  // a blanket interview_feedback_admin_all policy that gave location_manager
  // the exact same unconditional, ungated read as owner/entity_admin — every
  // interviewer's draft was visible to any location_manager immediately, no
  // reveal gating at all. Feedback is now fetched separately via
  // get_application_interview_feedback(), see ApplicationInterviewFeedbackRow.
}

export interface Offer {
  id: string
  application_id: string
  position_id: string
  proposed_salary_amount: number
  proposed_start_date: string
  status: OfferStatus
  sent_by: string | null
  sent_at: string | null
  decided_at: string | null
  decision_reason: string | null
  converted_employee_id: string | null
  created_by: string | null
  created_at: string
  updated_at: string
}

export type InterviewFormat = 'in_person' | 'video' | 'phone'
export type InterviewFeedbackStatus = 'draft' | 'submitted' | 'reopened'
export type InterviewRecommendation = 'strong_yes' | 'yes' | 'neutral' | 'no' | 'strong_no'
export type MyInterviewState = 'upcoming' | 'completed' | 'feedback_submitted' | 'cancelled' | 'reopened'

// Row shape returned by the get_my_interviews() RPC — already a curated,
// minimum-necessary projection, not a raw table select.
export interface MyInterviewRow {
  interview_id: string
  candidate_name: string
  position_title: string
  scheduled_at: string
  format: InterviewFormat
  meeting_location: string | null
  stage_name: string
  state: MyInterviewState
  feedback_status: InterviewFeedbackStatus | null
}

export interface MyInterviewFeedback {
  status: InterviewFeedbackStatus
  recommendation: InterviewRecommendation | null
  competency_ratings: Record<string, number> | null
  strengths: string | null
  concerns: string | null
  notes: string | null
  submitted_at: string | null
  reopen_reason: string | null
  reopened_at: string | null
}

// Shape returned by get_interview_detail() — a curated jsonb object, not a
// raw join across candidates/job_applications/offers.
export interface MyInterviewDetail {
  id: string
  candidate_name: string
  position_title: string
  scheduled_at: string
  format: InterviewFormat
  meeting_location: string | null
  stage_name: string
  interview_guide: string | null
  cancelled_at: string | null
  cancellation_reason: string | null
  state: MyInterviewState
  feedback: MyInterviewFeedback | null
}

export interface CandidateFileRef {
  id: string
  file_type: 'resume' | 'interview_pack' | 'other'
  storage_path: string
}

// Row shape returned by get_application_interview_feedback() — the Recruiting
// module's reveal-gated replacement for a raw interviews/interview_feedback
// join (Phase 3.12). A "round" is every non-cancelled interview sharing the
// same (application_id, stage_id). For owner/entity_admin, feedback_visible
// is always true and every content field reflects the real row (or null if
// no feedback was ever saved). For location_manager, feedback_visible is
// only true once the round is revealed (every required interviewer submitted,
// or a Recruiting Admin/Owner closed the round) AND this specific row's own
// status is 'submitted' — a reopened row drops back out of view immediately.
// When feedback_visible is false, every content field below is null server-
// side; the client never receives it to redact.
export interface ApplicationInterviewFeedbackRow {
  interview_id: string
  stage_id: string
  stage_name: string
  sequence: number
  scheduled_at: string
  interviewer_id: string
  interviewer_name: string | null
  cancelled_at: string | null
  outcome: InterviewOutcome
  feedback_id: string | null
  feedback_status: InterviewFeedbackStatus | null
  feedback_visible: boolean
  recommendation: InterviewRecommendation | null
  competency_ratings: Record<string, number> | null
  strengths: string | null
  concerns: string | null
  notes: string | null
  submitted_at: string | null
  reopened_at: string | null
  reopen_reason: string | null
  round_revealed: boolean
  round_closed: boolean
  round_closed_by_name: string | null
  round_closed_at: string | null
  round_closed_reason: string | null
  round_required_count: number
  round_submitted_count: number
}

export type NotificationPriority = 'low' | 'normal' | 'high'

// Row shape returned by get_my_notifications() — a curated projection over
// the notifications table (see Phase 2.5 in the README). The table itself is
// select/update-only for authenticated users; every insert goes through the
// internal create_notification() writer called by the RPCs/triggers that
// raise these events, so there's no client-side "create notification" path.
export interface NotificationRow {
  id: string
  notification_type: string
  title: string
  message: string | null
  target_type: string | null
  target_id: string | null
  priority: NotificationPriority
  read_at: string | null
  resolved_at: string | null
  created_at: string
}

// Phase 2.7: clock-in/attendance — a record of actual time worked, matched
// to (never merged into) the planned shift. Deliberately separate from
// payroll: nothing here ever writes to timesheet_entries or payslips.
export type AttendanceExceptionType = 'missing_clock_out' | 'unmatched_shift' | 'no_shift_match'

// Row shape returned by get_attendance_exceptions() — a curated, already-
// classified projection, not a raw join.
export interface AttendanceException {
  exception_type: AttendanceExceptionType
  employee_id: string
  employee_name: string
  shift_date: string
  record_id: string | null
  shift_id: string | null
  clock_in_at: string | null
  clock_out_at: string | null
}

export interface AttendanceRecord {
  id: string
  entity_id: string
  location_id: string
  employee_id: string
  shift_id: string | null
  clock_in_at: string
  clock_out_at: string | null
  original_clock_in_at: string | null
  original_clock_out_at: string | null
  corrected: boolean
  correction_reason: string | null
  corrected_by: string | null
  corrected_at: string | null
  created_at: string
  updated_at: string
}

// Phase 2.9: idempotent leave accrual, gated behind an explicitly
// owner-approved policy per leave type. Configuring a policy always resets
// is_approved to false — a fresh, separate owner approval is required
// before run_leave_accrual() will do anything with it.
export type LeaveAccrualFrequency = 'monthly' | 'annual'
export type LeaveAccrualRounding = 'none' | 'nearest_half_day' | 'nearest_day'

export interface LeaveAccrualPolicy {
  id: string
  entity_id: string
  leave_type_id: string
  frequency: LeaveAccrualFrequency
  days_per_period: number
  rounding: LeaveAccrualRounding
  max_balance_days: number | null
  carry_forward_cap_days: number | null
  probation_days: number
  policy_start_date: string
  is_approved: boolean
  approved_by: string | null
  approved_at: string | null
  created_by: string | null
  created_at: string
  updated_at: string
  leave_types?: Pick<LeaveType, 'id' | 'name'> | null
}

export interface PayslipDeduction {
  id: string
  payroll_run_id: string
  employee_id: string
  deduction_type: string
  amount: number
  notes: string | null
  created_at: string
  employees?: Pick<Employee, 'id' | 'full_name'> | null
}
