#!/usr/bin/env node
// Build an idempotent SQL seed from help-content/articles/*.md and (optionally) upload screenshots.
//
//   node scripts/seed-help.mjs                 writes supabase/seed/help_articles_seed.sql
//   SUPABASE_SERVICE_ROLE_KEY=... node scripts/seed-help.mjs --upload
//                                              also uploads help-content/screenshots/*.png to the private help-media bucket
//
// Apply the SQL with the Supabase SQL editor / MCP execute_sql (it runs as the database owner).
// Re-running is safe: articles are upserted by slug and a new version is only created when the content changed.
// The service role key is read from the environment only; never commit it.
import { readFileSync, readdirSync, writeFileSync, mkdirSync, existsSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const articlesDir = join(root, 'help-content/articles')
const shotsDir = join(root, 'help-content/screenshots')
const outFile = join(root, 'supabase/seed/help_articles_seed.sql')
const SUPABASE_URL = process.env.SUPABASE_URL ?? 'https://yclhzwghzrohusqxfasq.supabase.co'
const CATEGORIES = ['getting-started', 'employee', 'manager', 'admin']
const ROLES = ['staff', 'shift_supervisor', 'location_manager', 'entity_admin', 'owner']

function parseList(v) {
  const t = v.trim()
  if (t === '' || t === '[]') return []
  return t.replace(/^\[|\]$/g, '').split(',').map((x) => x.trim().replace(/^["']|["']$/g, '')).filter(Boolean)
}

export function parseArticle(text, file) {
  const m = /^---\n([\s\S]*?)\n---\n?([\s\S]*)$/.exec(text.replace(/\r\n/g, '\n'))
  if (!m) throw new Error(`${file}: missing front matter`)
  const fm = {}
  let listKey = null
  for (const line of m[1].split('\n')) {
    const item = /^\s+-\s+(.*)$/.exec(line)
    if (item && listKey) {
      fm[listKey].push(item[1].trim())
      continue
    }
    const kv = /^([a-z_]+):\s*(.*)$/.exec(line)
    if (!kv) continue
    const [, k, v] = kv
    if (v === '' && ['audience', 'related'].includes(k)) {
      fm[k] = []
      listKey = k
    } else {
      listKey = null
      fm[k] = ['audience', 'related'].includes(k) ? parseList(v) : v.trim().replace(/^["']|["']$/g, '')
    }
  }
  return { fm, body: m[2].trim() }
}

function validate(fm, file) {
  const bad = []
  for (const k of ['title', 'slug', 'category', 'summary', 'last_reviewed']) if (!fm[k]) bad.push(`missing ${k}`)
  if (fm.category && !CATEGORIES.includes(fm.category)) bad.push(`bad category ${fm.category}`)
  if (!fm.audience?.length || fm.audience.some((a) => !ROLES.includes(a))) bad.push('bad audience')
  if (fm.last_reviewed && !/^\d{4}-\d{2}-\d{2}$/.test(fm.last_reviewed)) bad.push('last_reviewed must be YYYY-MM-DD')
  if (bad.length) throw new Error(`${file}: ${bad.join(', ')}`)
}

// Add the numbered legend from the manifest to each ![alt](shot:key) as the image title:  "1. Label | 2. Label"
function withLegends(body, manifest) {
  return body.replace(/!\[([^\]]*)\]\(shot:([a-z0-9][a-z0-9_-]*)\)/gi, (all, alt, key) => {
    const ann = manifest[key]?.annotations
    if (!ann?.length) return all
    const legend = ann.map((a) => `${a.n}. ${String(a.label).replace(/["|]/g, '')}`).join(' | ')
    return `![${alt}](shot:${key} "${legend}")`
  })
}

const q = (s) => `$hc$${s}$hc$`
const arr = (a) => `array[${a.map((x) => `'${x.replace(/'/g, "''")}'`).join(',')}]::text[]`

function build() {
  const manifestPath = join(shotsDir, 'manifest.json')
  const manifest = existsSync(manifestPath) ? JSON.parse(readFileSync(manifestPath, 'utf8')) : {}
  const files = readdirSync(articlesDir).filter((f) => f.endsWith('.md')).sort()
  const rows = []
  for (const f of files) {
    const { fm, body } = parseArticle(readFileSync(join(articlesDir, f), 'utf8'), f)
    validate(fm, f)
    if (fm.status && fm.status !== 'published') continue
    rows.push({ fm, body: withLegends(body, manifest) })
  }
  const slugs = new Set(rows.map((r) => r.fm.slug))
  for (const r of rows) for (const s of r.fm.related ?? []) if (!slugs.has(s)) console.warn(`warning: ${r.fm.slug} relates to unknown slug ${s}`)

  let sql = `-- Generated by scripts/seed-help.mjs from help-content/articles. Do not edit by hand; re-run the script.
-- Idempotent: upserts by slug; a new published version is created only when the content changed.
create or replace function pg_temp.seed_help_article(
  p_slug text, p_title text, p_category text, p_audience text[], p_summary text, p_body text,
  p_related text[], p_route text, p_reviewed date) returns text language plpgsql as $f$
declare a public.help_articles; changed boolean; v int; snap jsonb;
begin
  snap := jsonb_build_object('title', p_title, 'category', p_category, 'audience', to_jsonb(p_audience), 'summary', p_summary,
                             'body_md', p_body, 'related', to_jsonb(p_related), 'route', p_route);
  select * into a from public.help_articles where slug = p_slug;
  if not found then
    insert into public.help_articles (slug, title, category, audience, summary, body_md, related, route, status, last_reviewed, current_version)
    values (p_slug, p_title, p_category, p_audience, p_summary, p_body, p_related, p_route, 'published', p_reviewed, 1)
    returning * into a;
    insert into public.help_article_versions (article_id, version, snapshot, change_note) values (a.id, 1, snap, 'Imported from help-content');
    return p_slug || ': created v1';
  end if;
  changed := (a.title, a.category, a.audience, a.summary, a.body_md, a.related, a.route)
             is distinct from (p_title, p_category, p_audience, p_summary, p_body, p_related, p_route)
             or a.status <> 'published';
  if not changed then
    update public.help_articles set last_reviewed = greatest(coalesce(last_reviewed, p_reviewed), p_reviewed) where id = a.id and (last_reviewed is null or last_reviewed < p_reviewed);
    return p_slug || ': unchanged';
  end if;
  v := a.current_version + 1;
  update public.help_articles set title = p_title, category = p_category, audience = p_audience, summary = p_summary, body_md = p_body,
    related = p_related, route = p_route, status = 'published', draft = null, current_version = v, last_reviewed = p_reviewed, updated_at = now()
  where id = a.id;
  insert into public.help_article_versions (article_id, version, snapshot, change_note) values (a.id, v, snap, 'Updated from help-content');
  return p_slug || ': updated to v' || v;
end $f$;

select pg_temp.seed_help_article(slug, title, category, audience, summary, body, related, route, reviewed) from (values
`
  sql += rows
    .map(({ fm, body }) =>
      `  (${q(fm.slug)}, ${q(fm.title)}, ${q(fm.category)}, ${arr(fm.audience)}, ${q(fm.summary)}, ${q(body)}, ${arr(fm.related ?? [])}, ${fm.route ? q(fm.route) : 'null::text'}, date '${fm.last_reviewed}')`
    )
    .join(',\n')
  sql += `\n) as t(slug, title, category, audience, summary, body, related, route, reviewed);\n`
  return { sql, count: rows.length }
}

async function upload() {
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY
  if (!key) throw new Error('Set SUPABASE_SERVICE_ROLE_KEY in the environment to upload screenshots.')
  const files = readdirSync(shotsDir).filter((f) => f.endsWith('.png'))
  for (const f of files) {
    const res = await fetch(`${SUPABASE_URL}/storage/v1/object/help-media/${encodeURIComponent(f)}`, {
      method: 'POST',
      headers: { Authorization: `Bearer ${key}`, apikey: key, 'Content-Type': 'image/png', 'x-upsert': 'true' },
      body: readFileSync(join(shotsDir, f)),
    })
    console.log(`${res.ok ? 'uploaded' : 'FAILED  '} ${f}${res.ok ? '' : ` (${res.status} ${await res.text()})`}`)
  }
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const { sql, count } = build()
  mkdirSync(dirname(outFile), { recursive: true })
  writeFileSync(outFile, sql)
  console.log(`wrote ${count} articles to ${outFile.replace(root + '/', '')}`)
  if (process.argv.includes('--upload')) await upload()
}
